# STAGE 1: Exporting requirements.txt
FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml poetry.lock* ./

RUN poetry lock
RUN poetry self add poetry-plugin-export && \
    poetry export -f requirements.txt --without-hashes --output requirements.txt


# STAGE 2: Building final image
FROM python:3.12-slim

WORKDIR /api

COPY --from=builder /app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]
