"""added quantity and price columns

Revision ID: 7ec4073e0a9e
Revises: c18f1c649796
Create Date: 2025-11-03 22:40:25.738598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec4073e0a9e'
down_revision: Union[str, Sequence[str], None] = 'c18f1c649796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderedfoods', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orderedfoods', sa.Column('price', sa.Integer(), nullable=False))
    op.alter_column('restaurants', 'contact',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'contact',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('orderedfoods', 'price')
    op.drop_column('orderedfoods', 'quantity')
    # ### end Alembic commands ###
